# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api import backend_pb2 as api_dot_backend__pb2


class BackendServiceStub(object):
    """The BackendService implements APIs to generate matches and handle ticket assignments.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchMatches = channel.unary_stream(
                '/openmatch.BackendService/FetchMatches',
                request_serializer=api_dot_backend__pb2.FetchMatchesRequest.SerializeToString,
                response_deserializer=api_dot_backend__pb2.FetchMatchesResponse.FromString,
                )
        self.AssignTickets = channel.unary_unary(
                '/openmatch.BackendService/AssignTickets',
                request_serializer=api_dot_backend__pb2.AssignTicketsRequest.SerializeToString,
                response_deserializer=api_dot_backend__pb2.AssignTicketsResponse.FromString,
                )
        self.ReleaseTickets = channel.unary_unary(
                '/openmatch.BackendService/ReleaseTickets',
                request_serializer=api_dot_backend__pb2.ReleaseTicketsRequest.SerializeToString,
                response_deserializer=api_dot_backend__pb2.ReleaseTicketsResponse.FromString,
                )
        self.ReleaseAllTickets = channel.unary_unary(
                '/openmatch.BackendService/ReleaseAllTickets',
                request_serializer=api_dot_backend__pb2.ReleaseAllTicketsRequest.SerializeToString,
                response_deserializer=api_dot_backend__pb2.ReleaseAllTicketsResponse.FromString,
                )


class BackendServiceServicer(object):
    """The BackendService implements APIs to generate matches and handle ticket assignments.
    """

    def FetchMatches(self, request, context):
        """FetchMatches triggers a MatchFunction with the specified MatchProfile and
        returns a set of matches generated by the Match Making Function, and
        accepted by the evaluator.
        Tickets in matches returned by FetchMatches are moved from active to
        pending, and will not be returned by query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignTickets(self, request, context):
        """AssignTickets overwrites the Assignment field of the input TicketIds.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseTickets(self, request, context):
        """ReleaseTickets moves tickets from the pending state, to the active state.
        This enables them to be returned by query, and find different matches.
        BETA FEATURE WARNING:  This call and the associated Request and Response
        messages are not finalized and still subject to possible change or removal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseAllTickets(self, request, context):
        """ReleaseAllTickets moves all tickets from the pending state, to the active
        state. This enables them to be returned by query, and find different
        matches.
        BETA FEATURE WARNING:  This call and the associated Request and Response
        messages are not finalized and still subject to possible change or removal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BackendServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchMatches': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchMatches,
                    request_deserializer=api_dot_backend__pb2.FetchMatchesRequest.FromString,
                    response_serializer=api_dot_backend__pb2.FetchMatchesResponse.SerializeToString,
            ),
            'AssignTickets': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignTickets,
                    request_deserializer=api_dot_backend__pb2.AssignTicketsRequest.FromString,
                    response_serializer=api_dot_backend__pb2.AssignTicketsResponse.SerializeToString,
            ),
            'ReleaseTickets': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseTickets,
                    request_deserializer=api_dot_backend__pb2.ReleaseTicketsRequest.FromString,
                    response_serializer=api_dot_backend__pb2.ReleaseTicketsResponse.SerializeToString,
            ),
            'ReleaseAllTickets': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseAllTickets,
                    request_deserializer=api_dot_backend__pb2.ReleaseAllTicketsRequest.FromString,
                    response_serializer=api_dot_backend__pb2.ReleaseAllTicketsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openmatch.BackendService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BackendService(object):
    """The BackendService implements APIs to generate matches and handle ticket assignments.
    """

    @staticmethod
    def FetchMatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/openmatch.BackendService/FetchMatches',
            api_dot_backend__pb2.FetchMatchesRequest.SerializeToString,
            api_dot_backend__pb2.FetchMatchesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AssignTickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openmatch.BackendService/AssignTickets',
            api_dot_backend__pb2.AssignTicketsRequest.SerializeToString,
            api_dot_backend__pb2.AssignTicketsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReleaseTickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openmatch.BackendService/ReleaseTickets',
            api_dot_backend__pb2.ReleaseTicketsRequest.SerializeToString,
            api_dot_backend__pb2.ReleaseTicketsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReleaseAllTickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openmatch.BackendService/ReleaseAllTickets',
            api_dot_backend__pb2.ReleaseAllTicketsRequest.SerializeToString,
            api_dot_backend__pb2.ReleaseAllTicketsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
