# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api import evaluator_pb2 as api_dot_evaluator__pb2


class EvaluatorStub(object):
    """The Evaluator service implements APIs used to evaluate and shortlist matches proposed by MMFs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Evaluate = channel.stream_stream(
                '/openmatch.Evaluator/Evaluate',
                request_serializer=api_dot_evaluator__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=api_dot_evaluator__pb2.EvaluateResponse.FromString,
                )


class EvaluatorServicer(object):
    """The Evaluator service implements APIs used to evaluate and shortlist matches proposed by MMFs.
    """

    def Evaluate(self, request_iterator, context):
        """Evaluate evaluates a list of proposed matches based on quality, collision status, and etc, then shortlist the matches and returns the final results.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EvaluatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Evaluate': grpc.stream_stream_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=api_dot_evaluator__pb2.EvaluateRequest.FromString,
                    response_serializer=api_dot_evaluator__pb2.EvaluateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openmatch.Evaluator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Evaluator(object):
    """The Evaluator service implements APIs used to evaluate and shortlist matches proposed by MMFs.
    """

    @staticmethod
    def Evaluate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/openmatch.Evaluator/Evaluate',
            api_dot_evaluator__pb2.EvaluateRequest.SerializeToString,
            api_dot_evaluator__pb2.EvaluateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
