# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/evaluator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api import messages_pb2 as api_dot_messages__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pi/evaluator.proto\x12\topenmatch\x1a\x12\x61pi/messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"2\n\x0f\x45valuateRequest\x12\x1f\n\x05match\x18\x01 \x01(\x0b\x32\x10.openmatch.Match\"*\n\x10\x45valuateResponse\x12\x10\n\x08match_id\x18\x02 \x01(\tJ\x04\x08\x01\x10\x02\x32\x7f\n\tEvaluator\x12r\n\x08\x45valuate\x12\x1a.openmatch.EvaluateRequest\x1a\x1b.openmatch.EvaluateResponse\")\x82\xd3\xe4\x93\x02#\"\x1e/v1/evaluator/matches:evaluate:\x01*(\x01\x30\x01\x42\x8c\x03Z open-match.dev/open-match/pkg/pb\xaa\x02\tOpenMatch\x92\x41\xda\x02\x12\xb3\x01\n\tEvaluator\"I\n\nOpen Match\x12\x16https://open-match.dev\x1a#open-match-discuss@googlegroups.com*V\n\x12\x41pache 2.0 License\x12@https://github.com/googleforgames/open-match/blob/master/LICENSE2\x03\x31.0*\x02\x01\x02\x32\x10\x61pplication/json:\x10\x61pplication/jsonR;\n\x03\x34\x30\x34\x12\x34\n*Returned when the resource does not exist.\x12\x06\n\x04\x9a\x02\x01\x07r=\n\x18Open Match Documentation\x12!https://open-match.dev/site/docs/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.evaluator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z open-match.dev/open-match/pkg/pb\252\002\tOpenMatch\222A\332\002\022\263\001\n\tEvaluator\"I\n\nOpen Match\022\026https://open-match.dev\032#open-match-discuss@googlegroups.com*V\n\022Apache 2.0 License\022@https://github.com/googleforgames/open-match/blob/master/LICENSE2\0031.0*\002\001\0022\020application/json:\020application/jsonR;\n\003404\0224\n*Returned when the resource does not exist.\022\006\n\004\232\002\001\007r=\n\030Open Match Documentation\022!https://open-match.dev/site/docs/'
  _globals['_EVALUATOR'].methods_by_name['Evaluate']._options = None
  _globals['_EVALUATOR'].methods_by_name['Evaluate']._serialized_options = b'\202\323\344\223\002#\"\036/v1/evaluator/matches:evaluate:\001*'
  _globals['_EVALUATEREQUEST']._serialized_start=132
  _globals['_EVALUATEREQUEST']._serialized_end=182
  _globals['_EVALUATERESPONSE']._serialized_start=184
  _globals['_EVALUATERESPONSE']._serialized_end=226
  _globals['_EVALUATOR']._serialized_start=228
  _globals['_EVALUATOR']._serialized_end=355
# @@protoc_insertion_point(module_scope)
