# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api import frontend_pb2 as api_dot_frontend__pb2
from api import messages_pb2 as api_dot_messages__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FrontendServiceStub(object):
    """The FrontendService implements APIs to manage and query status of a Tickets.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTicket = channel.unary_unary(
                '/openmatch.FrontendService/CreateTicket',
                request_serializer=api_dot_frontend__pb2.CreateTicketRequest.SerializeToString,
                response_deserializer=api_dot_messages__pb2.Ticket.FromString,
                )
        self.DeleteTicket = channel.unary_unary(
                '/openmatch.FrontendService/DeleteTicket',
                request_serializer=api_dot_frontend__pb2.DeleteTicketRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetTicket = channel.unary_unary(
                '/openmatch.FrontendService/GetTicket',
                request_serializer=api_dot_frontend__pb2.GetTicketRequest.SerializeToString,
                response_deserializer=api_dot_messages__pb2.Ticket.FromString,
                )
        self.WatchAssignments = channel.unary_stream(
                '/openmatch.FrontendService/WatchAssignments',
                request_serializer=api_dot_frontend__pb2.WatchAssignmentsRequest.SerializeToString,
                response_deserializer=api_dot_frontend__pb2.WatchAssignmentsResponse.FromString,
                )
        self.AcknowledgeBackfill = channel.unary_unary(
                '/openmatch.FrontendService/AcknowledgeBackfill',
                request_serializer=api_dot_frontend__pb2.AcknowledgeBackfillRequest.SerializeToString,
                response_deserializer=api_dot_frontend__pb2.AcknowledgeBackfillResponse.FromString,
                )
        self.CreateBackfill = channel.unary_unary(
                '/openmatch.FrontendService/CreateBackfill',
                request_serializer=api_dot_frontend__pb2.CreateBackfillRequest.SerializeToString,
                response_deserializer=api_dot_messages__pb2.Backfill.FromString,
                )
        self.DeleteBackfill = channel.unary_unary(
                '/openmatch.FrontendService/DeleteBackfill',
                request_serializer=api_dot_frontend__pb2.DeleteBackfillRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetBackfill = channel.unary_unary(
                '/openmatch.FrontendService/GetBackfill',
                request_serializer=api_dot_frontend__pb2.GetBackfillRequest.SerializeToString,
                response_deserializer=api_dot_messages__pb2.Backfill.FromString,
                )
        self.UpdateBackfill = channel.unary_unary(
                '/openmatch.FrontendService/UpdateBackfill',
                request_serializer=api_dot_frontend__pb2.UpdateBackfillRequest.SerializeToString,
                response_deserializer=api_dot_messages__pb2.Backfill.FromString,
                )


class FrontendServiceServicer(object):
    """The FrontendService implements APIs to manage and query status of a Tickets.
    """

    def CreateTicket(self, request, context):
        """CreateTicket assigns an unique TicketId to the input Ticket and record it in state storage.
        A ticket is considered as ready for matchmaking once it is created.
        - If a TicketId exists in a Ticket request, an auto-generated TicketId will override this field.
        - If SearchFields exist in a Ticket, CreateTicket will also index these fields such that one can query the ticket with query.QueryTickets function.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTicket(self, request, context):
        """DeleteTicket immediately stops Open Match from using the Ticket for matchmaking and removes the Ticket from state storage.
        The client should delete the Ticket when finished matchmaking with it. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTicket(self, request, context):
        """GetTicket get the Ticket associated with the specified TicketId.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchAssignments(self, request, context):
        """WatchAssignments stream back Assignment of the specified TicketId if it is updated.
        - If the Assignment is not updated, GetAssignment will retry using the configured backoff strategy. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcknowledgeBackfill(self, request, context):
        """AcknowledgeBackfill is used to notify OpenMatch about GameServer connection info
        This triggers an assignment process.
        BETA FEATURE WARNING: This call and the associated Request and Response
        messages are not finalized and still subject to possible change or removal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBackfill(self, request, context):
        """CreateBackfill creates a new Backfill object.
        BETA FEATURE WARNING:  This call and the associated Request and Response
        messages are not finalized and still subject to possible change or removal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBackfill(self, request, context):
        """DeleteBackfill receives a backfill ID and deletes its resource.
        Any tickets waiting for this backfill will be returned to the active pool, no longer pending.
        BETA FEATURE WARNING:  This call and the associated Request and Response
        messages are not finalized and still subject to possible change or removal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBackfill(self, request, context):
        """GetBackfill returns a backfill object by its ID.
        BETA FEATURE WARNING:  This call and the associated Request and Response
        messages are not finalized and still subject to possible change or removal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBackfill(self, request, context):
        """UpdateBackfill updates search_fields and extensions for the backfill with the provided id.
        Any tickets waiting for this backfill will be returned to the active pool, no longer pending.
        BETA FEATURE WARNING:  This call and the associated Request and Response
        messages are not finalized and still subject to possible change or removal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrontendServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTicket,
                    request_deserializer=api_dot_frontend__pb2.CreateTicketRequest.FromString,
                    response_serializer=api_dot_messages__pb2.Ticket.SerializeToString,
            ),
            'DeleteTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTicket,
                    request_deserializer=api_dot_frontend__pb2.DeleteTicketRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTicket,
                    request_deserializer=api_dot_frontend__pb2.GetTicketRequest.FromString,
                    response_serializer=api_dot_messages__pb2.Ticket.SerializeToString,
            ),
            'WatchAssignments': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchAssignments,
                    request_deserializer=api_dot_frontend__pb2.WatchAssignmentsRequest.FromString,
                    response_serializer=api_dot_frontend__pb2.WatchAssignmentsResponse.SerializeToString,
            ),
            'AcknowledgeBackfill': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeBackfill,
                    request_deserializer=api_dot_frontend__pb2.AcknowledgeBackfillRequest.FromString,
                    response_serializer=api_dot_frontend__pb2.AcknowledgeBackfillResponse.SerializeToString,
            ),
            'CreateBackfill': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBackfill,
                    request_deserializer=api_dot_frontend__pb2.CreateBackfillRequest.FromString,
                    response_serializer=api_dot_messages__pb2.Backfill.SerializeToString,
            ),
            'DeleteBackfill': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBackfill,
                    request_deserializer=api_dot_frontend__pb2.DeleteBackfillRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetBackfill': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBackfill,
                    request_deserializer=api_dot_frontend__pb2.GetBackfillRequest.FromString,
                    response_serializer=api_dot_messages__pb2.Backfill.SerializeToString,
            ),
            'UpdateBackfill': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBackfill,
                    request_deserializer=api_dot_frontend__pb2.UpdateBackfillRequest.FromString,
                    response_serializer=api_dot_messages__pb2.Backfill.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openmatch.FrontendService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FrontendService(object):
    """The FrontendService implements APIs to manage and query status of a Tickets.
    """

    @staticmethod
    def CreateTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openmatch.FrontendService/CreateTicket',
            api_dot_frontend__pb2.CreateTicketRequest.SerializeToString,
            api_dot_messages__pb2.Ticket.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openmatch.FrontendService/DeleteTicket',
            api_dot_frontend__pb2.DeleteTicketRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openmatch.FrontendService/GetTicket',
            api_dot_frontend__pb2.GetTicketRequest.SerializeToString,
            api_dot_messages__pb2.Ticket.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WatchAssignments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/openmatch.FrontendService/WatchAssignments',
            api_dot_frontend__pb2.WatchAssignmentsRequest.SerializeToString,
            api_dot_frontend__pb2.WatchAssignmentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AcknowledgeBackfill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openmatch.FrontendService/AcknowledgeBackfill',
            api_dot_frontend__pb2.AcknowledgeBackfillRequest.SerializeToString,
            api_dot_frontend__pb2.AcknowledgeBackfillResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateBackfill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openmatch.FrontendService/CreateBackfill',
            api_dot_frontend__pb2.CreateBackfillRequest.SerializeToString,
            api_dot_messages__pb2.Backfill.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBackfill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openmatch.FrontendService/DeleteBackfill',
            api_dot_frontend__pb2.DeleteBackfillRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBackfill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openmatch.FrontendService/GetBackfill',
            api_dot_frontend__pb2.GetBackfillRequest.SerializeToString,
            api_dot_messages__pb2.Backfill.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBackfill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/openmatch.FrontendService/UpdateBackfill',
            api_dot_frontend__pb2.UpdateBackfillRequest.SerializeToString,
            api_dot_messages__pb2.Backfill.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
