// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api/frontend.proto

#include "api/frontend.pb.h"
#include "api/frontend.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace openmatch {

static const char* FrontendService_method_names[] = {
  "/openmatch.FrontendService/CreateTicket",
  "/openmatch.FrontendService/DeleteTicket",
  "/openmatch.FrontendService/GetTicket",
  "/openmatch.FrontendService/WatchAssignments",
  "/openmatch.FrontendService/AcknowledgeBackfill",
  "/openmatch.FrontendService/CreateBackfill",
  "/openmatch.FrontendService/DeleteBackfill",
  "/openmatch.FrontendService/GetBackfill",
  "/openmatch.FrontendService/UpdateBackfill",
};

std::unique_ptr< FrontendService::Stub> FrontendService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FrontendService::Stub> stub(new FrontendService::Stub(channel, options));
  return stub;
}

FrontendService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateTicket_(FrontendService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteTicket_(FrontendService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetTicket_(FrontendService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WatchAssignments_(FrontendService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_AcknowledgeBackfill_(FrontendService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateBackfill_(FrontendService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteBackfill_(FrontendService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetBackfill_(FrontendService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateBackfill_(FrontendService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FrontendService::Stub::CreateTicket(::grpc::ClientContext* context, const ::openmatch::CreateTicketRequest& request, ::openmatch::Ticket* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openmatch::CreateTicketRequest, ::openmatch::Ticket, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateTicket_, context, request, response);
}

void FrontendService::Stub::async::CreateTicket(::grpc::ClientContext* context, const ::openmatch::CreateTicketRequest* request, ::openmatch::Ticket* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openmatch::CreateTicketRequest, ::openmatch::Ticket, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateTicket_, context, request, response, std::move(f));
}

void FrontendService::Stub::async::CreateTicket(::grpc::ClientContext* context, const ::openmatch::CreateTicketRequest* request, ::openmatch::Ticket* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateTicket_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openmatch::Ticket>* FrontendService::Stub::PrepareAsyncCreateTicketRaw(::grpc::ClientContext* context, const ::openmatch::CreateTicketRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openmatch::Ticket, ::openmatch::CreateTicketRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateTicket_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openmatch::Ticket>* FrontendService::Stub::AsyncCreateTicketRaw(::grpc::ClientContext* context, const ::openmatch::CreateTicketRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateTicketRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FrontendService::Stub::DeleteTicket(::grpc::ClientContext* context, const ::openmatch::DeleteTicketRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openmatch::DeleteTicketRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteTicket_, context, request, response);
}

void FrontendService::Stub::async::DeleteTicket(::grpc::ClientContext* context, const ::openmatch::DeleteTicketRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openmatch::DeleteTicketRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteTicket_, context, request, response, std::move(f));
}

void FrontendService::Stub::async::DeleteTicket(::grpc::ClientContext* context, const ::openmatch::DeleteTicketRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteTicket_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* FrontendService::Stub::PrepareAsyncDeleteTicketRaw(::grpc::ClientContext* context, const ::openmatch::DeleteTicketRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::openmatch::DeleteTicketRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteTicket_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* FrontendService::Stub::AsyncDeleteTicketRaw(::grpc::ClientContext* context, const ::openmatch::DeleteTicketRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteTicketRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FrontendService::Stub::GetTicket(::grpc::ClientContext* context, const ::openmatch::GetTicketRequest& request, ::openmatch::Ticket* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openmatch::GetTicketRequest, ::openmatch::Ticket, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetTicket_, context, request, response);
}

void FrontendService::Stub::async::GetTicket(::grpc::ClientContext* context, const ::openmatch::GetTicketRequest* request, ::openmatch::Ticket* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openmatch::GetTicketRequest, ::openmatch::Ticket, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTicket_, context, request, response, std::move(f));
}

void FrontendService::Stub::async::GetTicket(::grpc::ClientContext* context, const ::openmatch::GetTicketRequest* request, ::openmatch::Ticket* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTicket_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openmatch::Ticket>* FrontendService::Stub::PrepareAsyncGetTicketRaw(::grpc::ClientContext* context, const ::openmatch::GetTicketRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openmatch::Ticket, ::openmatch::GetTicketRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetTicket_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openmatch::Ticket>* FrontendService::Stub::AsyncGetTicketRaw(::grpc::ClientContext* context, const ::openmatch::GetTicketRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetTicketRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::openmatch::WatchAssignmentsResponse>* FrontendService::Stub::WatchAssignmentsRaw(::grpc::ClientContext* context, const ::openmatch::WatchAssignmentsRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::openmatch::WatchAssignmentsResponse>::Create(channel_.get(), rpcmethod_WatchAssignments_, context, request);
}

void FrontendService::Stub::async::WatchAssignments(::grpc::ClientContext* context, const ::openmatch::WatchAssignmentsRequest* request, ::grpc::ClientReadReactor< ::openmatch::WatchAssignmentsResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::openmatch::WatchAssignmentsResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_WatchAssignments_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::openmatch::WatchAssignmentsResponse>* FrontendService::Stub::AsyncWatchAssignmentsRaw(::grpc::ClientContext* context, const ::openmatch::WatchAssignmentsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::openmatch::WatchAssignmentsResponse>::Create(channel_.get(), cq, rpcmethod_WatchAssignments_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::openmatch::WatchAssignmentsResponse>* FrontendService::Stub::PrepareAsyncWatchAssignmentsRaw(::grpc::ClientContext* context, const ::openmatch::WatchAssignmentsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::openmatch::WatchAssignmentsResponse>::Create(channel_.get(), cq, rpcmethod_WatchAssignments_, context, request, false, nullptr);
}

::grpc::Status FrontendService::Stub::AcknowledgeBackfill(::grpc::ClientContext* context, const ::openmatch::AcknowledgeBackfillRequest& request, ::openmatch::AcknowledgeBackfillResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openmatch::AcknowledgeBackfillRequest, ::openmatch::AcknowledgeBackfillResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AcknowledgeBackfill_, context, request, response);
}

void FrontendService::Stub::async::AcknowledgeBackfill(::grpc::ClientContext* context, const ::openmatch::AcknowledgeBackfillRequest* request, ::openmatch::AcknowledgeBackfillResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openmatch::AcknowledgeBackfillRequest, ::openmatch::AcknowledgeBackfillResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AcknowledgeBackfill_, context, request, response, std::move(f));
}

void FrontendService::Stub::async::AcknowledgeBackfill(::grpc::ClientContext* context, const ::openmatch::AcknowledgeBackfillRequest* request, ::openmatch::AcknowledgeBackfillResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AcknowledgeBackfill_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openmatch::AcknowledgeBackfillResponse>* FrontendService::Stub::PrepareAsyncAcknowledgeBackfillRaw(::grpc::ClientContext* context, const ::openmatch::AcknowledgeBackfillRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openmatch::AcknowledgeBackfillResponse, ::openmatch::AcknowledgeBackfillRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AcknowledgeBackfill_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openmatch::AcknowledgeBackfillResponse>* FrontendService::Stub::AsyncAcknowledgeBackfillRaw(::grpc::ClientContext* context, const ::openmatch::AcknowledgeBackfillRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAcknowledgeBackfillRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FrontendService::Stub::CreateBackfill(::grpc::ClientContext* context, const ::openmatch::CreateBackfillRequest& request, ::openmatch::Backfill* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openmatch::CreateBackfillRequest, ::openmatch::Backfill, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateBackfill_, context, request, response);
}

void FrontendService::Stub::async::CreateBackfill(::grpc::ClientContext* context, const ::openmatch::CreateBackfillRequest* request, ::openmatch::Backfill* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openmatch::CreateBackfillRequest, ::openmatch::Backfill, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateBackfill_, context, request, response, std::move(f));
}

void FrontendService::Stub::async::CreateBackfill(::grpc::ClientContext* context, const ::openmatch::CreateBackfillRequest* request, ::openmatch::Backfill* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateBackfill_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openmatch::Backfill>* FrontendService::Stub::PrepareAsyncCreateBackfillRaw(::grpc::ClientContext* context, const ::openmatch::CreateBackfillRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openmatch::Backfill, ::openmatch::CreateBackfillRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateBackfill_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openmatch::Backfill>* FrontendService::Stub::AsyncCreateBackfillRaw(::grpc::ClientContext* context, const ::openmatch::CreateBackfillRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateBackfillRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FrontendService::Stub::DeleteBackfill(::grpc::ClientContext* context, const ::openmatch::DeleteBackfillRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openmatch::DeleteBackfillRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteBackfill_, context, request, response);
}

void FrontendService::Stub::async::DeleteBackfill(::grpc::ClientContext* context, const ::openmatch::DeleteBackfillRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openmatch::DeleteBackfillRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteBackfill_, context, request, response, std::move(f));
}

void FrontendService::Stub::async::DeleteBackfill(::grpc::ClientContext* context, const ::openmatch::DeleteBackfillRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteBackfill_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* FrontendService::Stub::PrepareAsyncDeleteBackfillRaw(::grpc::ClientContext* context, const ::openmatch::DeleteBackfillRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::openmatch::DeleteBackfillRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteBackfill_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* FrontendService::Stub::AsyncDeleteBackfillRaw(::grpc::ClientContext* context, const ::openmatch::DeleteBackfillRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteBackfillRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FrontendService::Stub::GetBackfill(::grpc::ClientContext* context, const ::openmatch::GetBackfillRequest& request, ::openmatch::Backfill* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openmatch::GetBackfillRequest, ::openmatch::Backfill, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetBackfill_, context, request, response);
}

void FrontendService::Stub::async::GetBackfill(::grpc::ClientContext* context, const ::openmatch::GetBackfillRequest* request, ::openmatch::Backfill* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openmatch::GetBackfillRequest, ::openmatch::Backfill, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBackfill_, context, request, response, std::move(f));
}

void FrontendService::Stub::async::GetBackfill(::grpc::ClientContext* context, const ::openmatch::GetBackfillRequest* request, ::openmatch::Backfill* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBackfill_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openmatch::Backfill>* FrontendService::Stub::PrepareAsyncGetBackfillRaw(::grpc::ClientContext* context, const ::openmatch::GetBackfillRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openmatch::Backfill, ::openmatch::GetBackfillRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetBackfill_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openmatch::Backfill>* FrontendService::Stub::AsyncGetBackfillRaw(::grpc::ClientContext* context, const ::openmatch::GetBackfillRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetBackfillRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FrontendService::Stub::UpdateBackfill(::grpc::ClientContext* context, const ::openmatch::UpdateBackfillRequest& request, ::openmatch::Backfill* response) {
  return ::grpc::internal::BlockingUnaryCall< ::openmatch::UpdateBackfillRequest, ::openmatch::Backfill, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateBackfill_, context, request, response);
}

void FrontendService::Stub::async::UpdateBackfill(::grpc::ClientContext* context, const ::openmatch::UpdateBackfillRequest* request, ::openmatch::Backfill* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::openmatch::UpdateBackfillRequest, ::openmatch::Backfill, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateBackfill_, context, request, response, std::move(f));
}

void FrontendService::Stub::async::UpdateBackfill(::grpc::ClientContext* context, const ::openmatch::UpdateBackfillRequest* request, ::openmatch::Backfill* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateBackfill_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::openmatch::Backfill>* FrontendService::Stub::PrepareAsyncUpdateBackfillRaw(::grpc::ClientContext* context, const ::openmatch::UpdateBackfillRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::openmatch::Backfill, ::openmatch::UpdateBackfillRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateBackfill_, context, request);
}

::grpc::ClientAsyncResponseReader< ::openmatch::Backfill>* FrontendService::Stub::AsyncUpdateBackfillRaw(::grpc::ClientContext* context, const ::openmatch::UpdateBackfillRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateBackfillRaw(context, request, cq);
  result->StartCall();
  return result;
}

FrontendService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FrontendService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FrontendService::Service, ::openmatch::CreateTicketRequest, ::openmatch::Ticket, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FrontendService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openmatch::CreateTicketRequest* req,
             ::openmatch::Ticket* resp) {
               return service->CreateTicket(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FrontendService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FrontendService::Service, ::openmatch::DeleteTicketRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FrontendService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openmatch::DeleteTicketRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->DeleteTicket(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FrontendService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FrontendService::Service, ::openmatch::GetTicketRequest, ::openmatch::Ticket, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FrontendService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openmatch::GetTicketRequest* req,
             ::openmatch::Ticket* resp) {
               return service->GetTicket(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FrontendService_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< FrontendService::Service, ::openmatch::WatchAssignmentsRequest, ::openmatch::WatchAssignmentsResponse>(
          [](FrontendService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openmatch::WatchAssignmentsRequest* req,
             ::grpc::ServerWriter<::openmatch::WatchAssignmentsResponse>* writer) {
               return service->WatchAssignments(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FrontendService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FrontendService::Service, ::openmatch::AcknowledgeBackfillRequest, ::openmatch::AcknowledgeBackfillResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FrontendService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openmatch::AcknowledgeBackfillRequest* req,
             ::openmatch::AcknowledgeBackfillResponse* resp) {
               return service->AcknowledgeBackfill(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FrontendService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FrontendService::Service, ::openmatch::CreateBackfillRequest, ::openmatch::Backfill, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FrontendService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openmatch::CreateBackfillRequest* req,
             ::openmatch::Backfill* resp) {
               return service->CreateBackfill(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FrontendService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FrontendService::Service, ::openmatch::DeleteBackfillRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FrontendService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openmatch::DeleteBackfillRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->DeleteBackfill(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FrontendService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FrontendService::Service, ::openmatch::GetBackfillRequest, ::openmatch::Backfill, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FrontendService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openmatch::GetBackfillRequest* req,
             ::openmatch::Backfill* resp) {
               return service->GetBackfill(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FrontendService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FrontendService::Service, ::openmatch::UpdateBackfillRequest, ::openmatch::Backfill, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FrontendService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::openmatch::UpdateBackfillRequest* req,
             ::openmatch::Backfill* resp) {
               return service->UpdateBackfill(ctx, req, resp);
             }, this)));
}

FrontendService::Service::~Service() {
}

::grpc::Status FrontendService::Service::CreateTicket(::grpc::ServerContext* context, const ::openmatch::CreateTicketRequest* request, ::openmatch::Ticket* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FrontendService::Service::DeleteTicket(::grpc::ServerContext* context, const ::openmatch::DeleteTicketRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FrontendService::Service::GetTicket(::grpc::ServerContext* context, const ::openmatch::GetTicketRequest* request, ::openmatch::Ticket* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FrontendService::Service::WatchAssignments(::grpc::ServerContext* context, const ::openmatch::WatchAssignmentsRequest* request, ::grpc::ServerWriter< ::openmatch::WatchAssignmentsResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FrontendService::Service::AcknowledgeBackfill(::grpc::ServerContext* context, const ::openmatch::AcknowledgeBackfillRequest* request, ::openmatch::AcknowledgeBackfillResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FrontendService::Service::CreateBackfill(::grpc::ServerContext* context, const ::openmatch::CreateBackfillRequest* request, ::openmatch::Backfill* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FrontendService::Service::DeleteBackfill(::grpc::ServerContext* context, const ::openmatch::DeleteBackfillRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FrontendService::Service::GetBackfill(::grpc::ServerContext* context, const ::openmatch::GetBackfillRequest* request, ::openmatch::Backfill* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FrontendService::Service::UpdateBackfill(::grpc::ServerContext* context, const ::openmatch::UpdateBackfillRequest* request, ::openmatch::Backfill* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace openmatch

