# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api import matchfunction_pb2 as api_dot_matchfunction__pb2


class MatchFunctionStub(object):
    """The MatchFunction service implements APIs to run user-defined matchmaking logics.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_stream(
                '/openmatch.MatchFunction/Run',
                request_serializer=api_dot_matchfunction__pb2.RunRequest.SerializeToString,
                response_deserializer=api_dot_matchfunction__pb2.RunResponse.FromString,
                )


class MatchFunctionServicer(object):
    """The MatchFunction service implements APIs to run user-defined matchmaking logics.
    """

    def Run(self, request, context):
        """DO NOT CALL THIS FUNCTION MANUALLY. USE backend.FetchMatches INSTEAD.
        Run pulls Tickets that satisfy Profile constraints from QueryService,
        runs matchmaking logic against them, then constructs and streams back
        match candidates to the Backend service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatchFunctionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_stream_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=api_dot_matchfunction__pb2.RunRequest.FromString,
                    response_serializer=api_dot_matchfunction__pb2.RunResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openmatch.MatchFunction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MatchFunction(object):
    """The MatchFunction service implements APIs to run user-defined matchmaking logics.
    """

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/openmatch.MatchFunction/Run',
            api_dot_matchfunction__pb2.RunRequest.SerializeToString,
            api_dot_matchfunction__pb2.RunResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
