# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api import query_pb2 as api_dot_query__pb2


class QueryServiceStub(object):
    """The QueryService service implements helper APIs for Match Function to query Tickets from state storage.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryTickets = channel.unary_stream(
                '/openmatch.QueryService/QueryTickets',
                request_serializer=api_dot_query__pb2.QueryTicketsRequest.SerializeToString,
                response_deserializer=api_dot_query__pb2.QueryTicketsResponse.FromString,
                )
        self.QueryTicketIds = channel.unary_stream(
                '/openmatch.QueryService/QueryTicketIds',
                request_serializer=api_dot_query__pb2.QueryTicketIdsRequest.SerializeToString,
                response_deserializer=api_dot_query__pb2.QueryTicketIdsResponse.FromString,
                )
        self.QueryBackfills = channel.unary_stream(
                '/openmatch.QueryService/QueryBackfills',
                request_serializer=api_dot_query__pb2.QueryBackfillsRequest.SerializeToString,
                response_deserializer=api_dot_query__pb2.QueryBackfillsResponse.FromString,
                )


class QueryServiceServicer(object):
    """The QueryService service implements helper APIs for Match Function to query Tickets from state storage.
    """

    def QueryTickets(self, request, context):
        """QueryTickets gets a list of Tickets that match all Filters of the input Pool.
        - If the Pool contains no Filters, QueryTickets will return all Tickets in the state storage.
        QueryTickets pages the Tickets by `queryPageSize` and stream back responses.
        - queryPageSize is default to 1000 if not set, and has a minimum of 10 and maximum of 10000.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTicketIds(self, request, context):
        """QueryTicketIds gets the list of TicketIDs that meet all the filtering criteria requested by the pool.
        - If the Pool contains no Filters, QueryTicketIds will return all TicketIDs in the state storage.
        QueryTicketIds pages the TicketIDs by `queryPageSize` and stream back responses.
        - queryPageSize is default to 1000 if not set, and has a minimum of 10 and maximum of 10000.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryBackfills(self, request, context):
        """QueryBackfills gets a list of Backfills.
        BETA FEATURE WARNING:  This call and the associated Request and Response
        messages are not finalized and still subject to possible change or removal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryTickets': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryTickets,
                    request_deserializer=api_dot_query__pb2.QueryTicketsRequest.FromString,
                    response_serializer=api_dot_query__pb2.QueryTicketsResponse.SerializeToString,
            ),
            'QueryTicketIds': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryTicketIds,
                    request_deserializer=api_dot_query__pb2.QueryTicketIdsRequest.FromString,
                    response_serializer=api_dot_query__pb2.QueryTicketIdsResponse.SerializeToString,
            ),
            'QueryBackfills': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryBackfills,
                    request_deserializer=api_dot_query__pb2.QueryBackfillsRequest.FromString,
                    response_serializer=api_dot_query__pb2.QueryBackfillsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openmatch.QueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QueryService(object):
    """The QueryService service implements helper APIs for Match Function to query Tickets from state storage.
    """

    @staticmethod
    def QueryTickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/openmatch.QueryService/QueryTickets',
            api_dot_query__pb2.QueryTicketsRequest.SerializeToString,
            api_dot_query__pb2.QueryTicketsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryTicketIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/openmatch.QueryService/QueryTicketIds',
            api_dot_query__pb2.QueryTicketIdsRequest.SerializeToString,
            api_dot_query__pb2.QueryTicketIdsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryBackfills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/openmatch.QueryService/QueryBackfills',
            api_dot_query__pb2.QueryBackfillsRequest.SerializeToString,
            api_dot_query__pb2.QueryBackfillsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
