# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/query.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api import messages_pb2 as api_dot_messages__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61pi/query.proto\x12\topenmatch\x1a\x12\x61pi/messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"4\n\x13QueryTicketsRequest\x12\x1d\n\x04pool\x18\x01 \x01(\x0b\x32\x0f.openmatch.Pool\":\n\x14QueryTicketsResponse\x12\"\n\x07tickets\x18\x01 \x03(\x0b\x32\x11.openmatch.Ticket\"6\n\x15QueryTicketIdsRequest\x12\x1d\n\x04pool\x18\x01 \x01(\x0b\x32\x0f.openmatch.Pool\"%\n\x16QueryTicketIdsResponse\x12\x0b\n\x03ids\x18\x01 \x03(\t\"6\n\x15QueryBackfillsRequest\x12\x1d\n\x04pool\x18\x01 \x01(\x0b\x32\x0f.openmatch.Pool\"@\n\x16QueryBackfillsResponse\x12&\n\tbackfills\x18\x01 \x03(\x0b\x32\x13.openmatch.Backfill2\x9a\x03\n\x0cQueryService\x12|\n\x0cQueryTickets\x12\x1e.openmatch.QueryTicketsRequest\x1a\x1f.openmatch.QueryTicketsResponse\")\x82\xd3\xe4\x93\x02#\"\x1e/v1/queryservice/tickets:query:\x01*0\x01\x12\x84\x01\n\x0eQueryTicketIds\x12 .openmatch.QueryTicketIdsRequest\x1a!.openmatch.QueryTicketIdsResponse\"+\x82\xd3\xe4\x93\x02%\" /v1/queryservice/ticketids:query:\x01*0\x01\x12\x84\x01\n\x0eQueryBackfills\x12 .openmatch.QueryBackfillsRequest\x1a!.openmatch.QueryBackfillsResponse\"+\x82\xd3\xe4\x93\x02%\" /v1/queryservice/backfills:query:\x01*0\x01\x42\x98\x03Z open-match.dev/open-match/pkg/pb\xaa\x02\tOpenMatch\x92\x41\xe6\x02\x12\xbf\x01\n\x15MM Logic (Data Layer)\"I\n\nOpen Match\x12\x16https://open-match.dev\x1a#open-match-discuss@googlegroups.com*V\n\x12\x41pache 2.0 License\x12@https://github.com/googleforgames/open-match/blob/master/LICENSE2\x03\x31.0*\x02\x01\x02\x32\x10\x61pplication/json:\x10\x61pplication/jsonR;\n\x03\x34\x30\x34\x12\x34\n*Returned when the resource does not exist.\x12\x06\n\x04\x9a\x02\x01\x07r=\n\x18Open Match Documentation\x12!https://open-match.dev/site/docs/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.query_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z open-match.dev/open-match/pkg/pb\252\002\tOpenMatch\222A\346\002\022\277\001\n\025MM Logic (Data Layer)\"I\n\nOpen Match\022\026https://open-match.dev\032#open-match-discuss@googlegroups.com*V\n\022Apache 2.0 License\022@https://github.com/googleforgames/open-match/blob/master/LICENSE2\0031.0*\002\001\0022\020application/json:\020application/jsonR;\n\003404\0224\n*Returned when the resource does not exist.\022\006\n\004\232\002\001\007r=\n\030Open Match Documentation\022!https://open-match.dev/site/docs/'
  _globals['_QUERYSERVICE'].methods_by_name['QueryTickets']._options = None
  _globals['_QUERYSERVICE'].methods_by_name['QueryTickets']._serialized_options = b'\202\323\344\223\002#\"\036/v1/queryservice/tickets:query:\001*'
  _globals['_QUERYSERVICE'].methods_by_name['QueryTicketIds']._options = None
  _globals['_QUERYSERVICE'].methods_by_name['QueryTicketIds']._serialized_options = b'\202\323\344\223\002%\" /v1/queryservice/ticketids:query:\001*'
  _globals['_QUERYSERVICE'].methods_by_name['QueryBackfills']._options = None
  _globals['_QUERYSERVICE'].methods_by_name['QueryBackfills']._serialized_options = b'\202\323\344\223\002%\" /v1/queryservice/backfills:query:\001*'
  _globals['_QUERYTICKETSREQUEST']._serialized_start=128
  _globals['_QUERYTICKETSREQUEST']._serialized_end=180
  _globals['_QUERYTICKETSRESPONSE']._serialized_start=182
  _globals['_QUERYTICKETSRESPONSE']._serialized_end=240
  _globals['_QUERYTICKETIDSREQUEST']._serialized_start=242
  _globals['_QUERYTICKETIDSREQUEST']._serialized_end=296
  _globals['_QUERYTICKETIDSRESPONSE']._serialized_start=298
  _globals['_QUERYTICKETIDSRESPONSE']._serialized_end=335
  _globals['_QUERYBACKFILLSREQUEST']._serialized_start=337
  _globals['_QUERYBACKFILLSREQUEST']._serialized_end=391
  _globals['_QUERYBACKFILLSRESPONSE']._serialized_start=393
  _globals['_QUERYBACKFILLSRESPONSE']._serialized_end=457
  _globals['_QUERYSERVICE']._serialized_start=460
  _globals['_QUERYSERVICE']._serialized_end=870
# @@protoc_insertion_point(module_scope)
